#!/bin/bash

export template_name="MVVM-RxSwift"

mkdir -p ~/Library/Developer/Xcode/Templates/File\ Templates/$template_name
rm -rf ~/Library/Developer/Xcode/Templates/File\ Templates/$template_name
cp -R ./$template_name ~/Library/Developer/Xcode/Templates/File\ Templates/
echo "########## INSTALLED ##########"

